CREATE TABLE IF NOT EXISTS meetings (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL CHECK (title <> ''),
    meeting_date date NOT NULL,
    init_time time NOT NULL,
    end_time time NOT NULL,
    description text
);


INSERT INTO meetings(title, meeting_date, init_time, end_time, description)
    VALUES('Job interview', '2019-10-30', '10:00', '11:00', 'Software developer job offer');

INSERT INTO meetings(title, meeting_date, init_time, end_time, description)
    VALUES('Team meeting', '2019-11-01', '14:30', '16:00', 'Talk about currect projects status');

INSERT INTO meetings(title, meeting_date, init_time, end_time, description)
    VALUES('Clients meeting', '2019-11-10', '12:30', '14:00', 'Meeting with clients');